services:
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=my_database"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=myuser"
      - "TZ=Europe/Stockholm"
    command: --default-time-zone=Europe/Stockholm
    ports:
      - "3306:3306"
    volumes:
      - todo-data:/var/lib/mysql

  backend:
    build: ./todo-backend
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mysql

volumes:
  todo-data:
