spring:
  application:
    name: "todo-backend"

  datasource:
    url: "jdbc:mysql://mysql:3306/my_database"
    username: "root"
    password: "verysecret"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    date-format: yyy-MM-dd HH:mm
    time-zone: Europe/Stockholm